<?php

//////////////////////////////////////
//       			    //
// @author John Cummings            //
// Super globals homework for IS218 //
// Note some super_globals are not  //
// able to be used within this      //
// scripts scope.                   //
//            			    //
//////////////////////////////////////


// $GLOBALS allows you to use/reference all of the variables that are available
// in the entire program compared to local variables only available inside 
// a function. Returns it as an array with the variable names as keys.
function test() {
  $foo = "local variable";

  echo '$foo in global scope: ' . $GLOBALS["foo"] . "\n";
  echo '<br>';
  echo '$foo in current scope: ' . $foo . "\n";
} 

$foo = "Example content";
test();

echo '<br>';
// $_SERVER is an array that is generated by the web server which contains
// information about the server, the requests, the user.
// Information such as type of requests, server IP, userIP, etc.
echo '<br>$_SERVER variable: <br>';
echo $_SERVER['SERVER_NAME'];
echo '<br>';
echo 'Timestamp: ' . $_SERVER['REQUEST_TIME'];
echo '<br>';
echo 'Date: ' . date('F j, Y, g:i:s a', $_SERVER['REQUEST_TIME']);
echo '<br>';
echo $_SERVER['REMOTE_ADDR'];

// $_GET is an array of all the variables that were passed into the current
// php script via the URL parameters. If no URL parameters are passed then it
// will be an empty array
echo '<br><br>$_GET: For this example to work click this <a href="' .
$_SERVER['PHP_SELF'] . '?name=Jack">link</a>';
echo '<br>Hello ' . htmlspecialchars($_GET["name"]) . '!';

//$_POST is an array of all the variables that were passed into the current
// php script though the HTTP POST method which are encoded inside the HTTP

echo '<br><br>$_POST:<br>Hello ' . htmlspecialchars($_POST["name"]) . '!';
echo '<br>This will not work because no POST variables are being sent.';
echo '<br><br>';

// $_FILES is an array of all the files that are uploaded/used via the POST
// method
echo '<br>$_FILES<br>';
echo '<br>' . print_r($_FILES);
echo '<br>This is empty because there are no files being passed into the php
file.';

// $_COOKIE allows you to access the array of variables which are passed
// to the current script via HTTP cookies
$cookie_name = 'name';
$cookie_value = 'John';
setcookie($cookie_name, $cookie_value, time() + (86400*30), "/");
echo '<br>$_COOKIE<br>';
echo '<br>Hello ' . htmlspecialchars($_COOKIE["name"]) . '!';

// $_SESSION superglobal is an array of all of the session variables
// available to the current script
session_start();
$_SESSION['color'] = 'blue';
$_SESSION['name'] = 'John';

echo '<br>';
echo $_SESSION['name'] . ' likes the color ' . $_SESSION['color'];
echo '<br>';

// S_REQUEST has ALL of the contents of $_GET, $_POST, and $_COOKIE all 
// put together into one array
echo '<br><br>';
var_dump($_REQUEST); //This won't do anything because there was no variables
// Passed before runtime

// $_ENV is an array of variables which were passed into the current 
// script from the environment method. They are almost like the
// GLOBAL global variables in a way.
echo '<br><br>';
echo 'My username is ' . $_ENV["USER"] . '!';
echo '<br>';

?>
